# Yahoo - Forex

### Para instalação, execute:

In [4]:
#!pip install yfinance

### Exemplo de código:

In [2]:
import yfinance as yf

# Defina o ticker da ação (por exemplo, "EURUSD" para Apple)
ticker = "EURUSD=X"

# Baixe os dados históricos
data = yf.download(ticker, start="2023-01-01", end="2024-01-01", interval='1d')

# Exiba
data

[*********************100%***********************]  1 of 1 completed

                Open      High       Low     Close  Adj Close  Volume
Date
2023-01-02  1.070973  1.071237  1.065326  1.070973   1.070973       0
2023-01-03  1.067771  1.068262  1.052155  1.067771   1.067771       0
2023-01-04  1.054685  1.063151  1.054596  1.054685   1.054685       0
2023-01-05  1.060637  1.063264  1.051558  1.060637   1.060637       0
2023-01-06  1.052222  1.062225  1.048526  1.052222   1.052222       0
...              ...       ...       ...       ...        ...     ...
2023-12-25  1.102657  1.104240  1.099989  1.102657   1.102657       0
2023-12-26  1.102026  1.103997  1.100958  1.102026   1.102026       0
2023-12-27  1.104301  1.112248  1.102925  1.104301   1.104301       0
2023-12-28  1.110864  1.113945  1.107101  1.110864   1.110864       0
2023-12-29  1.106819  1.108647  1.104326  1.106819   1.106819       0

[260 rows x 6 columns]

# VectorBT - Crypto

### Para instalação, execute:

In [14]:
#!pip install python-binance
#!pip install vectorbt

### Exemplo de código:

In [33]:
import vectorbt as vbt

# Definir o símbolo BTCUSDT
symbol = 'BTCUSDT'


# Baixar dados com intervalos de 15 minutos usando VectorBT
cripto_data = vbt.BinanceData.download(
    symbol,
    start='7 day ago UTC', 
    end='now UTC',
    interval='15m'
)

# Exibir os dados
data = cripto_data.get()
data.tail()

0it [00:00, ?it/s]

,Open,High,Low,Close,Volume,Close time,Quote volume,Number of trades,Taker base volume,Taker quote volume
Open time,,,,,,,,,,
2024-09-21 00:00:00+00:00,63201.05,63201.06,63040.0,63071.18,87.38980,2024-09-21 00:14:59.999000+00:00,5.516427e+06,19032,39.94689,2.521735e+06
2024-09-21 00:15:00+00:00,63071.19,63300.00,63058.0,63120.65,164.89048,2024-09-21 00:29:59.999000+00:00,1.042256e+07,38904,94.38239,5.966003e+06
2024-09-21 00:30:00+00:00,63120.66,63310.37,63090.0,63252.91,222.59158,2024-09-21 00:44:59.999000+00:00,1.407689e+07,30515,123.43178,7.803835e+06
2024-09-21 00:45:00+00:00,63252.90,63271.50,63174.0,63174.00,109.64269,2024-09-21 00:59:59.999000+00:00,6.931334e+06,22227,53.15607,3.360278e+06
2024-09-21 01:00:00+00:00,63174.01,63200.00,63174.0,63188.24,21.94321,2024-09-21 01:14:59.999000+00:00,1.386528e+06,4479,11.52006,7.279252e+05